Only check the DCO on the author's commits
Signed-off-by: He Jie Xu <hejie.xu@intel.com>

diff --git a/support/hooks/pre-push b/support/hooks/pre-push
--- a/support/hooks/pre-push
+++ b/support/hooks/pre-push
@@ -12,6 +12,7 @@
 DUMMY_SHA=0000000000000000000000000000000000000000
 
 echo "Running pre-push check; to skip this step use 'push --no-verify'"
+AUTHOR=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/\1/p')
 
 # shellcheck disable=SC2034
 while read -r LOCAL_REF LOCAL_SHA REMOTE_REF REMOTE_SHA
@@ -30,6 +31,22 @@ do
     else
       # Updating branch. Verify new commits.
       RANGE="$REMOTE_SHA..$LOCAL_SHA"
+    fi
+
+    # Verify DCO signoff. We do this before the format checker, since it has
+    # some probability of failing spuriously, while this check never should.
+    #
+    # In general, we can't assume that the commits are signed off by author
+    # pushing, so we settle for just checking that there is a signoff at all.
+    SIGNED_OFF=$(git rev-list --no-merges --author "$AUTHOR" --grep "^Signed-off-by: " "$RANGE")
+    NOT_SIGNED_OFF=$(git rev-list --no-merges --author "$AUTHOR" "$RANGE" | grep -Fxv "$SIGNED_OFF")
+    if [ -n "$NOT_SIGNED_OFF" ]
+    then
+      echo >&2 "ERROR: The following commits do not have DCO signoff:"
+      while read -r commit; do
+        echo "  $(git log --pretty=oneline --abbrev-commit -n 1 "$commit")"
+      done <<< "$NOT_SIGNED_OFF"
+      exit 1
     fi
 
     # NOTE: The `tools` directory will be the same relative to the support
