deps/ci: Catch errors in precheck ci
This tool desperately needs some work and is prone to failure

Signed-off-by: Ryan Northey <ryan@synca.io>

diff --git a/.github/actions/do_ci/action.yml b/.github/actions/do_ci/action.yml
--- a/.github/actions/do_ci/action.yml
+++ b/.github/actions/do_ci/action.yml
@@ -35,6 +35,10 @@ inputs:
   command_ci:
     type: string
     default: ./ci/do_ci.sh
+  catch-errors:
+    type: boolean
+    default: false
+
 
   env:
     type: string
@@ -72,11 +76,23 @@ runs:
       fi
 
       if [[ -n "${{ inputs.command_prefix }}" ]]; then
-          ${{ inputs.command_prefix }} '${{ inputs.command_ci }} ${{ inputs.target }}'
+          COMMAND=(
+              ${{ inputs.command_prefix }}
+              '${{ inputs.command_ci }} ${{ inputs.target }}')
       else
-          ${{ inputs.command_ci }} ${{ inputs.target }}
+          COMMAND=(
+              ${{ inputs.command_ci }}
+              ${{ inputs.target }})
       fi
 
+      TMP_OUTPUT=$(mktemp)
+      "${COMMAND[@]}" 2> >(tee "$TMP_OUTPUT")
+      if [[ $? -ne 0 ]]; then
+          echo ":error: ${TMP_OUTPUT}"
+          if [[ ${{ inputs.catch-errors }} == "false" ]]; then
+              exit 1
+          fi
+      fi
       if [[ ${{ github.event_name }} == "pull_request" ]]; then
           export BAZEL_FAKE_SCM_REVISION=e3b4a6e9570da15ac1caffdded17a8bebdc7dfc9
           export CI_TARGET_BRANCH="${{ github.event.base.ref }}"
