github/precheck: Fix/improve error handling (#30500)
Signed-off-by: Ryan Northey <ryan@synca.io>
Signed-off-by: Sean Killeen <SeanKilleen@gmail.com>

diff --git a/.github/actions/do_ci/action.yml b/.github/actions/do_ci/action.yml
--- a/.github/actions/do_ci/action.yml
+++ b/.github/actions/do_ci/action.yml
@@ -84,21 +84,23 @@ runs:
               ${{ inputs.command_ci }}
               ${{ inputs.target }})
       fi
-
-      TMP_OUTPUT=$(mktemp)
-      "${COMMAND[@]}" 2> >(tee "$TMP_OUTPUT")
-      if [[ $? -ne 0 ]]; then
-          echo ":error: ${TMP_OUTPUT}"
-          if [[ ${{ inputs.catch-errors }} == "false" ]]; then
-              exit 1
-          fi
-      fi
       if [[ ${{ github.event_name }} == "pull_request" ]]; then
           export BAZEL_FAKE_SCM_REVISION=e3b4a6e9570da15ac1caffdded17a8bebdc7dfc9
           export CI_TARGET_BRANCH="${{ github.event.base.ref }}"
       else
           export CI_TARGET_BRANCH="${{ github.ref }}"
       fi
+      TMP_OUTPUT=$(mktemp)
+      "${COMMAND[@]}" 2> >(tee "$TMP_OUTPUT") || {
+          OUTPUT="$(cat "$TMP_OUTPUT" | sed 's/\n/%0A/g')"
+          rm -rf "$TMP_OUTPUT"
+          echo ":error: ${OUTPUT}"
+          if [[ ${{ inputs.catch-errors }} == "false" ]]; then
+              exit 1
+          fi
+
+      }
+      rm -rf "$TMP_OUTPUT"
     shell: bash
     env:
       GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
