ci: Fail PRs if branch VERSION.txt is not open
Signed-off-by: Ryan Northey <ryan@synca.io>

diff --git a/.azure-pipelines/pipelines.yml b/.azure-pipelines/pipelines.yml
--- a/.azure-pipelines/pipelines.yml
+++ b/.azure-pipelines/pipelines.yml
@@ -113,10 +113,23 @@ stages:
       name: changed
 
     - bash: |
+        set -e
         VERSION_DEV="$(cat VERSION.txt | cut -d- -f2)"
         if [[ $VERSION_DEV == "dev" ]]; then
             echo "##vso[task.setvariable variable=isDev;isoutput=true]true"
         else
+            if [[ $(Build.Reason) == "PullRequest" ]]; then
+                # Check to make sure that it was this PR that changed the version, otherwise fail
+                # as the branch needs to be reopened first.
+                # NB: this will not stop a PR that has already passed checks from being landed.
+                DIFF_TARGET_BRANCH="origin/$(System.PullRequest.TargetBranch)"
+                DIFF_REF="$(git merge-base HEAD "${DIFF_TARGET_BRANCH}")"
+                CHANGES="$(git diff "$DIFF_REF" HEAD VERSION.txt)"
+                if [[ -z "$CHANGES" ]]; then
+                    echo "VERSION.txt is not a development version. Please re-open the branch before making further changes" >&2
+                    exit 1
+                fi
+            fi
             echo "##vso[task.setvariable variable=isDev;isoutput=true]false"
         fi
       displayName: Set development/release env
